test_that("credential stores mutate one entry without losing other entries", {
  f <- auth_fixture(); on.exit(unlink(f$home, recursive = TRUE))
  store <- credential_store(path = f$path, env = f$env)
  expect_identical(as_json(store$read()), '{}')
  expect_null(store$get("missing"))
  store$mutate("one", function(current) json_object(access = "private", extension = NULL))
  store$mutate("two", function(current) json_object(access = "other"))
  store$mutate("one", function(current) { current$refresh <- "rotated"; current })
  expect_identical(store$get("one")$refresh, "rotated")
  expect_identical(store$get("two")$access, "other")
  before <- as_json(store$read())
  store$mutate("one", function(current) NULL)
  expect_identical(as_json(store$read()), before)
  expect_error(store$mutate("one", function(current) stop("private")), class = "AuthError")
  expect_identical(as_json(store$read()), before)
  store$remove("one")
  expect_null(store$get("one"))
  expect_identical(store$get("two")$access, "other")
})
