# One declaration per canonical shape. Constructor validation and JSON
# reading use this same table; wire adapters never define canonical types.
.schemas <- list(
  ApiKey = c(value = "string"),
  BearerToken = c(value = "string", expires_at = "string?"),
  AwsCredentials = c(access_key_id = "string", secret_access_key = "string", session_token = "string?", expires_at = "string?"),
  ContinuationState = c(provider = "string", kind = "string", data = "object"),
  TextPart = c(text = "text", continuation = "ContinuationState[]"),
  ThinkingPart = c(text = "text", continuation = "ContinuationState[]"),
  RefusalPart = c(text = "string", continuation = "ContinuationState[]"),
  CitationPart = c(url = "string?", title = "string?", text = "string?", continuation = "ContinuationState[]"),
  ImagePart = c(media_type = "string", data = "base64?", url = "string?", file_id = "string?", path = "string?", detail = "detail?", continuation = "ContinuationState[]"),
  AudioPart = c(media_type = "string", data = "base64?", url = "string?", file_id = "string?", path = "string?", continuation = "ContinuationState[]"),
  VideoPart = c(media_type = "string", data = "base64?", url = "string?", file_id = "string?", path = "string?", continuation = "ContinuationState[]"),
  DocumentPart = c(media_type = "string", data = "base64?", url = "string?", file_id = "string?", path = "string?", continuation = "ContinuationState[]"),
  BinaryPart = c(media_type = "string", data = "base64?", url = "string?", file_id = "string?", path = "string?", continuation = "ContinuationState[]"),
  ToolCallPart = c(id = "string", name = "string", input = "object", continuation = "ContinuationState[]"),
  ToolResultPart = c(id = "string", content = "Part[]", name = "string?", is_error = "bool", continuation = "ContinuationState[]"),
  Message = c(role = "role", parts = "Part[]", continuation = "ContinuationState[]"),
  TextDelta = c(text = "text", part_index = "nonnegative", logprobs = "TokenLogprob[]"),
  ThinkingDelta = c(text = "text", part_index = "nonnegative"),
  AudioDelta = c(data = "text?", url = "text?", file_id = "text?", part_index = "nonnegative", media_type = "string?"),
  ImageDelta = c(data = "text?", url = "text?", file_id = "text?", part_index = "nonnegative", media_type = "string?"),
  ToolCallDelta = c(input = "text", part_index = "nonnegative", id = "string?", name = "string?"),
  CitationDelta = c(text = "text?", url = "text?", title = "text?", part_index = "nonnegative"),
  ContinuationDelta = c(provider = "string", kind = "string", data = "object", part_index = "nonnegative?"),
  StreamStartEvent = c(id = "string?", model = "string?", adaptations = "Adaptation[]"),
  Adaptation = c(field = "string", action = "adaptation_action", reason = "string", asked = "json?", applied = "json?"),
  StreamDeltaEvent = c(delta = "Delta"),
  StreamEndEvent = c(finish_reason = "finish?", usage = "Usage?", provider_data = "object?"),
  StreamErrorEvent = c(error = "ErrorDetail"),
  ErrorDetail = c(code = "code", message = "text", provider_code = "string?"),
  FunctionTool = c(name = "string", description = "text?", parameters = "object"),
  BuiltinTool = c(name = "string", config = "object?"),
  ToolChoice = c(mode = "tool_mode", allowed = "string[]", parallel = "bool?"),
  Reasoning = c(effort = "effort", thinking_budget = "positive?", summary = "summary?"),
  CacheConfig = c(mode = "cache_mode", retention = "retention?", key = "string?", prefix_until_index = "nonnegative?", prefix = "prefix?", resource = "string?"),
  Config = c(max_tokens = "positive?", temperature = "float_nonnegative?", top_p = "probability?", top_k = "positive?", seed = "int?", frequency_penalty = "penalty?", presence_penalty = "penalty?", stop = "string[]", response_format = "object?", tool_choice = "ToolChoice?", reasoning = "Reasoning?", cache = "CacheConfig?", service_tier = "string?", user_id = "string?", store = "bool?", logprobs = "nonnegative?", extensions = "object?"),
  Request = c(model = "string", messages = "Message[]", system = "system?", tools = "Tool[]", config = "Config"),
  Usage = c(input_tokens = "nonnegative?", output_tokens = "nonnegative?", total_tokens = "nonnegative?", cache_read_tokens = "nonnegative?", cache_write_tokens = "nonnegative?", reasoning_tokens = "nonnegative?", input_audio_tokens = "nonnegative?", output_audio_tokens = "nonnegative?"),
  Response = c(id = "string?", model = "string", message = "Message", finish_reason = "finish", usage = "Usage", logprobs = "TokenLogprob[]", provider_data = "object?", adaptations = "Adaptation[]"),
  TopLogprob = c(token = "text", logprob = "float", bytes = "nonnegative[]", token_id = "int?"),
  TokenLogprob = c(token = "text", logprob = "float", bytes = "nonnegative[]", token_id = "int?", top = "TopLogprob[]"),
  FileUploadRequest = c(filename = "string", bytes_data = "raw?", media_type = "string", extensions = "object?", path = "string?"),
  FileInfo = c(id = "string", filename = "string?", media_type = "string?", size_bytes = "nonnegative?", created_at = "string?", expires_at = "string?", readiness = "readiness", downloadable = "bool?", provider_data = "object?"),
  FilePage = c(items = "FileInfo[]", next_cursor = "string?"),
  CacheInfo = c(id = "string", model = "string", tokens = "nonnegative?", created_at = "string?", expires_at = "string?", label = "string?", provider_data = "object?"),
  CachePage = c(items = "CacheInfo[]", next_cursor = "string?"),
  CachedPrefix = c(prefix = "Request", resource = "CacheInfo?"),
  BatchRequest = c(model = "string?", requests = "Request[]", label = "string?", extensions = "object?"),
  BatchJobInfo = c(id = "string", status = "batch_status", label = "string?", created_at = "string?", provider_data = "object?"),
  BatchEntry = c(index = "nonnegative", outcome = "batch_outcome", response = "Response?", error = "ErrorDetail?"),
  ImageGenerationRequest = c(model = "string", prompt = "string", size = "string?", images = "ImagePart[]", extensions = "object?"),
  ImageGenerationResponse = c(images = "ImagePart[]", text = "string?", id = "string?", model = "string?", usage = "Usage", provider_data = "object?"),
  SpeechGenerationRequest = c(model = "string", prompt = "string", voice = "string?", format = "string?", extensions = "object?"),
  SpeechGenerationResponse = c(audio = "AudioPart", id = "string?", model = "string?", usage = "Usage", provider_data = "object?"),
  VideoGenerationRequest = c(model = "string", prompt = "string", seconds = "positive?", images = "ImagePart[]", extensions = "object?"),
  VideoJobInfo = c(id = "string", status = "video_status", progress = "percentage?", created_at = "string?", model = "string?", provider_data = "object?"),
  AudioFormat = c(encoding = "encoding", sample_rate = "positive", channels = "positive"),
  LiveConfig = c(model = "string", system = "system?", tools = "Tool[]", voice = "string?", input_format = "AudioFormat?", output_format = "AudioFormat?", extensions = "object?"),
  LiveClientTurnEvent = c(parts = "Part[]", turn_complete = "bool"),
  LiveClientAudioEvent = c(data = "base64", media_type = "string"),
  LiveClientImageEvent = c(data = "base64", media_type = "string"),
  LiveClientTextEvent = c(text = "text"),
  LiveClientToolResultEvent = c(id = "string", content = "Part[]"),
  LiveClientInterruptEvent = character(),
  LiveClientEndAudioEvent = character(),
  LiveServerAudioEvent = c(data = "base64", media_type = "string?"),
  LiveServerTextEvent = c(text = "text"),
  LiveServerToolCallEvent = c(id = "string", name = "string", input = "object"),
  LiveServerToolCallDeltaEvent = c(input_delta = "text", id = "string?", name = "string?"),
  LiveServerInterruptedEvent = character(),
  LiveServerTurnEndEvent = c(usage = "Usage"),
  LiveServerUsageEvent = c(usage = "Usage"),
  LiveServerErrorEvent = c(error = "ErrorDetail"),
  ToolCallInfo = c(id = "string", name = "string", input = "object"),
  InferencePricing = c(input_per_million = "float_nonnegative?", output_per_million = "float_nonnegative?", cache_read_per_million = "float_nonnegative?", cache_write_per_million = "float_nonnegative?", currency = "string", dimensions = "object?"),
  InferenceModelInfo = c(input_modalities = "string[]", output_modalities = "string[]", context_window = "positive?", max_output_tokens = "positive?", supports_reasoning = "bool", reasoning_efforts = "string[]", pricing = "InferencePricing?", extensions = "object?"),
  ModelOrigin = c(type = "string", id = "string?", base_model = "string?", provider_data = "object?"),
  ModelInfo = c(id = "string", provider = "string", api_family = "string", aliases = "string[]", origin = "ModelOrigin", inference = "InferenceModelInfo?", extensions = "object?")
)

.unions <- list(
  Credential = c(api_key = "ApiKey", bearer_token = "BearerToken", aws = "AwsCredentials"),
  Part = c(text = "TextPart", thinking = "ThinkingPart", refusal = "RefusalPart", citation = "CitationPart", image = "ImagePart", audio = "AudioPart", video = "VideoPart", document = "DocumentPart", binary = "BinaryPart", tool_call = "ToolCallPart", tool_result = "ToolResultPart"),
  Delta = c(text = "TextDelta", thinking = "ThinkingDelta", image = "ImageDelta", audio = "AudioDelta", tool_call = "ToolCallDelta", citation = "CitationDelta", continuation = "ContinuationDelta"),
  StreamEvent = c(start = "StreamStartEvent", delta = "StreamDeltaEvent", end = "StreamEndEvent", error = "StreamErrorEvent"),
  Tool = c("function" = "FunctionTool", builtin = "BuiltinTool"),
  LiveClientEvent = c(turn = "LiveClientTurnEvent", audio = "LiveClientAudioEvent", image = "LiveClientImageEvent", text = "LiveClientTextEvent", tool_result = "LiveClientToolResultEvent", interrupt = "LiveClientInterruptEvent", end_audio = "LiveClientEndAudioEvent"),
  LiveServerEvent = c(audio = "LiveServerAudioEvent", text = "LiveServerTextEvent", tool_call = "LiveServerToolCallEvent", tool_call_delta = "LiveServerToolCallDeltaEvent", interrupted = "LiveServerInterruptedEvent", turn_end = "LiveServerTurnEndEvent", usage = "LiveServerUsageEvent", error = "LiveServerErrorEvent")
)

.vocab <- list(
  role = c("user", "assistant", "tool", "developer"),
  finish = c("stop", "length", "tool_call", "content_filter", "error"),
  effort = c("off", "minimal", "low", "medium", "high", "xhigh", "max"),
  adaptation_action = c("dropped", "clamped", "substituted", "client_side", "satisfied", "defaulted"),
  summary = c("auto", "concise", "detailed"), tool_mode = c("auto", "required", "none"),
  cache_mode = c("auto", "off"), retention = c("short", "long"), prefix = c("stable", "history"),
  detail = c("low", "high", "auto"), encoding = c("pcm16", "opus", "mp3", "aac"),
  readiness = c("pending", "ready", "failed"), batch_status = c("queued", "running", "cancelling", "completed", "failed", "cancelled", "expired"),
  batch_outcome = c("succeeded", "errored", "cancelled", "expired"), video_status = c("queued", "running", "completed", "failed", "cancelled"),
  code = c("auth", "billing", "rate_limit", "invalid_request", "context_length", "timeout", "server", "unsupported_model", "unsupported_feature", "not_configured", "unknown_model", "ambiguous_model", "transport", "lock_timeout", "stream_assembly", "provider")
)

.kind_names <- c(credential = "Credential", part = "Part", message = "Message", tool = "Tool", tool_choice = "ToolChoice", reasoning = "Reasoning", config = "Config", cache_config = "CacheConfig", cache_info = "CacheInfo", cache_page = "CachePage", cached_prefix = "CachedPrefix", token_logprob = "TokenLogprob", continuation_state = "ContinuationState", error_detail = "ErrorDetail", delta = "Delta", usage = "Usage", stream_event = "StreamEvent", request = "Request", response = "Response", model_info = "ModelInfo", batch_request = "BatchRequest", batch_job = "BatchJobInfo", batch_entry = "BatchEntry", file_upload_request = "FileUploadRequest", file_info = "FileInfo", file_page = "FilePage", image_generation_request = "ImageGenerationRequest", image_generation_response = "ImageGenerationResponse", speech_generation_request = "SpeechGenerationRequest", speech_generation_response = "SpeechGenerationResponse", video_generation_request = "VideoGenerationRequest", video_job = "VideoJobInfo", audio_format = "AudioFormat", live_config = "LiveConfig", live_client_event = "LiveClientEvent", live_server_event = "LiveServerEvent")
